import { expect, test, type Page } from '@playwright/test'
async function join(page: Page, nickname: string) {
  await page.goto('/')
  await page.getByLabel('Nickname').fill(nickname)
  await page.getByRole('button', { name: 'Enter The Kennel' }).click()
  await expect(page.getByRole('heading', { name: 'Grand Final Squares' })).toBeVisible()
  await page.getByRole('button', { name: 'The Kennel', exact: true }).click()
}
async function login(page: Page) {
  await page.goto('/host')
  await page.getByLabel('Host PIN').fill('2468')
  await page.getByRole('button', { name: 'Open console' }).click()
}
test('phone Kennel loop, payout spending, undo, pause, siren and projector', async ({ page, context }) => {
  const errors: string[] = []
  context.on('page', (p) => p.on('pageerror', (e) => errors.push(e.message)))
  page.on('pageerror', (e) => errors.push(e.message))
  await page.setViewportSize({ width: 360, height: 800 })
  await join(page, 'Alice')
  await expect(page.locator('.bones-card > strong')).toHaveText('1,500')
  const host = await context.newPage(); await login(host)
  await host.getByRole('button', { name: 'Start Q1' }).click()
  await page.getByRole('button', { name: 'Home', exact: true }).click()
  await page.getByRole('button', { name: '+50', exact: true }).click()
  await expect(page.getByText(/Your position: Home · 50 Bones/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Away', exact: true })).toBeDisabled()
  // Separate guest session, shared synthetic server state; a new tab keeps the existing guest token.
  const bob = await context.newPage(); await bob.goto('/')
  await bob.getByRole('button', { name: /Alice 2 squares/ }).click()
  await bob.getByLabel('Nickname').fill('Bob')
  await bob.getByRole('button', { name: 'Enter The Kennel' }).click()
  await bob.getByRole('button', { name: 'The Kennel', exact: true }).click()
  await bob.getByRole('button', { name: 'Away', exact: true }).click()
  await bob.getByRole('button', { name: '+100', exact: true }).click()
  await expect(bob.getByText(/Your position: Away · 100 Bones/)).toBeVisible()
  await host.getByRole('button', { name: 'Home goal', exact: false }).click()
  await expect(page.locator('.bones-card > strong')).toHaveText('1,600')
  await expect(bob.locator('.bones-card > strong')).toHaveText('1,400')
  await page.getByRole('button', { name: 'Home', exact: true }).click()
  await page.getByRole('button', { name: '+100', exact: true }).click()
  await host.getByRole('button', { name: /Undo last score/ }).click()
  await expect(page.locator('.bones-card > strong')).toHaveText('1,450')
  await expect(page.getByText(/Your position: Home · 50 Bones/)).toBeVisible()
  await host.getByRole('button', { name: 'Pause betting', exact: true }).click()
  await expect(page.getByRole('button', { name: '+25', exact: true })).toBeDisabled()
  await host.getByRole('button', { name: 'Away behind', exact: false }).click()
  await expect(host.getByText('0.1 (1)')).toBeVisible()
  await host.getByRole('button', { name: 'Resume betting', exact: true }).click()
  await page.evaluate(() => window.dispatchEvent(new Event('offline')))
  await expect(page.getByRole('button', { name: '+25', exact: true })).toBeDisabled()
  await page.evaluate(() => window.dispatchEvent(new Event('online')))
  await expect(page.getByRole('button', { name: '+25', exact: true })).toBeEnabled()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `/tmp/kennel-phase-two-${test.info().project.name}-360.png`, fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await host.getByRole('button', { name: 'Home goal', exact: false }).click()
  await host.getByRole('button', { name: 'Sound Q1 siren' }).click()
  await page.getByRole('button', { name: 'Ladder', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Q1 · final standings' })).toBeVisible()
  await expect(page.locator('.ladder-me').first()).toContainText('+100')
  const screen = await context.newPage(); await screen.setViewportSize({ width: 1920, height: 1080 }); await screen.goto('/screen')
  await expect(screen.getByRole('heading', { name: 'Grand Final Squares' })).toBeVisible()
  await expect(screen.getByRole('heading', { name: 'Q1 · top five' })).toBeVisible()
  await screen.screenshot({ path: `/tmp/kennel-phase-two-${test.info().project.name}-projector.png`, fullPage: true })
  expect(await screen.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight)).toBe(true)
  expect(errors).toEqual([])
})
test('host recovery confirms a winner or a refund and opens a fresh market', async ({ page }) => {
  await login(page); await page.getByRole('button', { name: 'Start Q1' }).click()
  await page.getByLabel('Winning team').selectOption({ label: 'Home' })
  await page.getByRole('button', { name: 'Review settlement' }).click()
  await page.getByRole('button', { name: 'Confirm settlement' }).click()
  await page.getByRole('button', { name: 'Open recovery Next Goal' }).click()
  await page.getByLabel('Refund reason').fill('Unresolvable play')
  await page.getByRole('button', { name: 'Review void and refund' }).click()
  await expect(page.getByText(/Reason: Unresolvable play/)).toBeVisible()
  await page.getByRole('button', { name: 'Confirm refund' }).click()
  await expect(page.getByRole('button', { name: 'Open recovery Next Goal' })).toBeEnabled()
})
